import { App } from "./Apps"
/*
 {
        id: ,
        name: '',
        urlApp: '',
        urlLogo: '',
        subTitle: '',
        functionality: 3,
        applicability: 6,
        originality: 9,
        ease: 4,
        views: ,
        likes: ,
        description: '',
        categories: [],
        tags: [],
        typology: [],
        Sign_up_to_create_products: "",
        Sign_up_to_access_artefacts: "",
        Registration_notes: "",
        Plan_and_Pricing: "",
        Free_plan_limits: "",
        Catalog_of_user_contents: "",
        Available_in_Italian_language: "",
        Advertisement: "",
        Complexity: ,
        Bloom_level: [],
        Documentation: [],
        Product_examples: [],
        Specific_subjects: [],
        urlPresentazione: '',
        urlTutorial: '',      
        presentation:[
            "",
            "/assets/ImagesPresentation//review1_1.png",
            "",
            "",
        ],
    },
*/


export const AppDbExample: App[] = [
    {
        id: 1,
        name: 'ABCya',
        urlApp: 'https://whiteboard.fi',
        urlLogo: 'https://drive.google.com/uc?id=1T0Tk_guSHmUheucp-3xr85kMeOXWE8xT&export=download',
        subTitle: 'Collection of educational tools',
        functionality: 3,
        applicability: 6,
        originality: 9,
        ease: 4,
        views: 50,
        likes: 0,
        description: 'ABCya is a site that offers educational games and activities for children in school age.The games are organized by grade level (from preschool to fifth grade of primary school). This portal offers a lot of interactive games for each school level and type of activity. It’s in English.',
        categories: ["Gamification", "Others"],
        tags: ["game", "kid", "student", "primary", "class", "study", "teacher", "gamification", "activity", "exercise", "learn", "learning"],
        typology: ["Web app"],
        Sign_up_to_create_products: "Optional",
        Sign_up_to_access_artefacts: "No registration",
        Registration_notes: "The games are free from PC, while if you are using a mobile device, you have to start a paid registration.",
        Plan_and_Pricing: "https://www.abcya.com/subscribe",
        Free_plan_limits: "Free account only using a PC.",
        Catalog_of_user_contents: "Public",
        Available_in_Italian_language: "No",
        Advertisement: "Yes",
        Complexity: 4,
        Bloom_level: ["Remember", "Understand", "Apply"],
        Documentation: ["Another tutorial: ", "https://www.youtube.com/watch?v=r-E4scXeXxs", "FAQ/Help page: ", "https://www.abcya.com/faq/#general"],
        Product_examples: ["Examples from the official page:", "https://www.abcya.com/games/alphabet_matching_game"],
        Specific_subjects: [],
        urlPresentazione: 'https://www.youtube.com/watch?v=tKwhcH87YZ4&list=PLXvp1RJPZGU4sn0vVotIV_wspo3cUWbNU&index=63',
        urlTutorial: 'https://www.youtube.com/watch?v=ilRVU6gGCYw',
        presentation: [
            "The first screen that appears when you open the site, allows you to choose the grade of scholarization on which the games will be based.",
            "/assets/ImagesPresentation/ABCya/review1_1.png",
            "After that, you can choose among different types of activities for the games, for example: “letters”, “numbers”, “strategy games”...",
            "/assets/ImagesPresentation/ABCya/review1_2.png",
            "By clicking on the activity, there will be a screen allowing to choose the game you want to start. .",
            "/assets/ImagesPresentation/ABCya/review1_3.png",
            'By clicking "GO AD-FREE" you can also use a paid version. There will just be a lot more games than the free version. It is not possible to create new games.',
        ],
        score: 4.5,
    },
    {
        id: 2,
        name: 'ActionBound',
        urlApp: 'https://www.storyjumper.com',
        urlLogo: 'https://drive.google.com/uc?id=1CP1SStHfUSvIidFagkRKcwMUWop2JYt5&export=download',
        subTitle: 'Create scavenger hunts for mobile devices',
        functionality: 3,
        applicability: 6,
        originality: 9,
        ease: 4,
        views: 86,
        likes: 0,
        description: 'ActionBound is a mixed application (Web and mobile) to build and participate in scavenger hunts in geographical or virtual places. The purpose of ActionBound is the exploration of the territory and the knowledge of its environment, but also an opportunity to introduce gamification techniques for tourism promotion or training. To build a Bound you can use the Web application that allows you to create routes, which can be enjoyed later on mobile devices. You will need to navigate the territory using a compass or GPS, gain points during the mission and complete the hunt in the shortest possible time.',
        categories: ["Gamification", "Others", "Designing & Planning", "Quizzes, forms, surveys", "Storytelling"],
        tags: ["treasure", "hunt", "explore", "area", "path", "quiz"],
        typology: ["Web app", "Android App", "IOS App"],
        Sign_up_to_create_products: "Compulsory",
        Sign_up_to_access_artefacts: "No registration",
        Registration_notes: "Registration is free for personal use and it’s necessary to create Bounds but not to use the public Bounds of the app.",
        Plan_and_Pricing: "https://en.actionbound.com/pricing",
        Free_plan_limits: "If you use the app as a private account it’s free. Other profiles need a payment.",
        Catalog_of_user_contents: "Public",
        Available_in_Italian_language: "Yes",
        Advertisement: "No",
        Complexity: 6,
        Bloom_level: ["Remember", "Understand", "Analyze", "Evaluate", "Create"],
        Documentation: ["slides about the app : ", "https://www.slideshare.net/busracelebisoy/creating-treasure-hunt-with-actionbound"],
        Product_examples: ["Example of scavenger hunt", "https://de.actionbound.com/bound/rainbowlecce"],
        Specific_subjects: [],
        urlPresentazione: 'https://www.youtube.com/watch?v=HDxEjGR4uY8&list=PLXvp1RJPZGU4sn0vVotIV_wspo3cUWbNU&index=17',
        urlTutorial: 'https://www.youtube.com/watch?v=V2VEKH6dNJM',
        presentation: [
            "The site has a user-friendly interface, at the bottom of the page there is a little demo video. The menu items exhaustively define the different functions within the site, such as: the inclusion of a new user, or the display of public Bounds.",
            "/assets/ImagesPresentation/ActionBound/review2_1.png",
            "The “public Bounds” page shows the different Bounds and select the available routes in your area.",
            "/assets/ImagesPresentation/ActionBound/review2_2.png",
            "Once logged in you can access to different tools of the menu to see and create new Bounds.",
            "/assets/ImagesPresentation/ActionBound/review2_3.png",
            "By clicking on “Create Bound” you’ll see the following screens where you can complete your Bound, adding some general information and single activities such as quizzes or missions. This is the first screen that appears when we create a new quiz.",
            "/assets/ImagesPresentation/ActionBound/review2_4.png",
            "This is another page for the creation of a quiz.",
            "/assets/ImagesPresentation/ActionBound/review2_5.png",
            "In addition to the quizzes, we can see on the right of the image below, all the other activities that can be added to the Bound.",
            "/assets/ImagesPresentation/ActionBound/review2_6.png",
            "Finally, you see this screen with all your activities. Now the bound is ready to be used and can be activated.",
            "/assets/ImagesPresentation/ActionBound/review2_7.png",
            "To start plaing you need the mobile app. It looks like this:",
            "/assets/ImagesPresentation/ActionBound/review2_8.png",
            "The easiest way to start a Bound is to frame the QR code provided on the website that can also be printed and given to the participants. On the mobile application, the graphic is simple and effective, presenting with these icons the various menu items.",
            "/assets/ImagesPresentation/ActionBound/review2_9.png",
            "/assets/ImagesPresentation/ActionBound/review2_10.png",
            "In the settings you can choose the language and access the account created on the site.",
            "/assets/ImagesPresentation/ActionBound/review2_11.png",
            "/assets/ImagesPresentation/ActionBound/review2_12.png",
            "/assets/ImagesPresentation/ActionBound/review2_13.png",
            'In the "Neighbouring Bounds" section you will see a map that displays the various Bounds close to where you are (blue dot on the map) and interact with them to start the hunt.',
            "/assets/ImagesPresentation/ActionBound/review2_14.png",
            "In the menu, there is a wide range of choices, you can search a bound by name, by category, to view your Bounds, view new users’ Bounds, and the best bounds made by the various users (mainly Germans).",
        ],
        score: 4.2,
    },
    {
        id: 3,
        name: 'Bitmoji',
        urlApp: 'https://whiteboard.fi',
        urlLogo: 'https://drive.google.com/uc?id=1T0Tk_guSHmUheucp-3xr85kMeOXWE8xT&export=download',
        subTitle: 'Create an avatar',
        functionality: 3,
        applicability: 6,
        originality: 9,
        ease: 4,
        views: 67,
        likes: 5,
        description: 'The company that created the application Bitstrips offres now an application to create emoticon. A feature that distinguishes them from the old emoticons is that those could be used only in chat / sms while the new ones have several uses including Social Media. The application is customizable from the first use, in fact, when you create your account you can create your avatar that looks like you and change it if you do not recognize yourself in it. Personalization is not only physical, but the application is very attentive to your outfit too.',
        categories: ["Diagrams, graphics and images", "Others"],
        tags: ["personal", "avatar", "emoticon", "emoji", "social"],
        typology: ["Web app", "Android App", "IOS App"],
        Sign_up_to_create_products: "Compulsory",
        Sign_up_to_access_artefacts: "Compulsory",
        Registration_notes: "To create a user account you have to register or authenticate with your own Google account (using Chrome browser), or you can use the mobile App, available on iOS and Android. Once your Bitmoji account is ready you can integrate it to your Facebook account.",
        Plan_and_Pricing: "",
        Free_plan_limits: "No limits, it’s totally free",
        Catalog_of_user_contents: "Protected",
        Available_in_Italian_language: "No",
        Advertisement: "No",
        Complexity: 2,
        Bloom_level: ["Apply", "Create"],
        Documentation: ["Spanish tutorial showing how to link Bitmoji to Snapchat ", "https://www.youtube.com/watch?v=FdR3IUE_FGM&t=15s", "English tutorial, how to activate the keyboard: ", "https://www.youtube.com/watch?v=WnoyWzAIGHo", "Video with explanation about Bitmoji use on Snapchat.", "https://www.tecnocino.it/2016/07/articolo/come-usare-bitmoji-su-snapchat-guida/79811/", "Slide presentation about the app’s features", "https://www.tecnocino.it/2015/04/articolo/bitmoji-cos-e-e-come-funziona-l-applicazione/60815/"],
        Product_examples: ["Avatar example", "http://a1.mzstatic.com/eu/r30/Purple22/v4/12/7b/59/127b59cd-9d54-0ac3-223f-3e08d9b54947/screen696x696.jpeg", "example of use of the avatar as a Keyboard to send messages", "https://imag.malavida.com/mvimgbig/download-fs/bitmoji-14842-3.jpg", "Example of avatar used on Social Media Snapchat", "http://cdn.mobilesyrup.com/wp-content/uploads/2016/07/bitmoji-2.jpg"],
        Specific_subjects: [],
        urlPresentazione: 'https://www.youtube.com/watch?v=tCAzsmpGTyM&list=PLXvp1RJPZGU4sn0vVotIV_wspo3cUWbNU&index=68',
        urlTutorial: 'https://www.youtube.com/watch?v=jZPUbfaLKEY',
        presentation: [
            "Bitmoji, an input method developed and designed by Bitstrips, which will give users the ability to communicate using their own personal avatar.",
            "/assets/ImagesPresentation/Bitmoji/review12_1.png",
            "Just as all external keyboards, to use Avatar Bitstrips in messages sent with iOS you need to install the application from the App Store. After downloading Bitmoji, you will need to activate it, just as you do for emoticons: to do this you must go in the iOS Settings, to the keyboard section, and select the Keyboard item. Now just select Bitmoji and it’ s activated.",
            "/assets/ImagesPresentation/Bitmoji/review12_2.png",
            "After this procedure, the Bidstrips keyboard will be immediately usable and, just like the emoticons one, to activate it you need to select the icon of the “globe” positioned on the left of the space bar, but before you begin to communicate with the Bitstrips avatar you will need to create your character: to do this you have to start the application that accompanies the keyboard and complete the guided procedure through which you can choose gender, skin color and all the other features of your virtual character.",
            "/assets/ImagesPresentation/Bitmoji/review12_3.png",
            "Despite Bitmoji is in fact usable as a real keyboard, its structure is quite different from traditional keyboards. Actually Bitmoji will give the opportunity to users to access the images database, select the one that suits better to what you want to communicate, download it and copy it to your device memory: to send the emoji with Avatar Bitstrips in iOS you must paste it in the textbox, and the contents will be sent as an image. But beware: just as with animated Gif, sending a Bistrips avatar via Messages app to a person who does not have an iPhone, will turn the text message to a MMS. How to create Bitmoji on Snapchat The first step to begin to create and use your own personal Bitmoji on Snapchat, is to update the latest version of Snapchat and then download the application Bitmoji. Once downloaded and installed on your smartphone Bitmoji, you start the app and log in with Snapchat account credentials to occur the integration so you can start to create your own avatar, looking for characteristics that are closest to yours.",
            "/assets/ImagesPresentation/Bitmoji/review12_4.png",
            "The customization options of Bitmoji are so many (also with regard to the clothing) that at the end of your creation, the character should actually look like you. Follow the instructions that appear on the display and set all the required features. When you’ve finished customizing your Bitmoji, you can save it and start using it on Snapchat. The Bitmoji can be sent in chat messages, or applied in the Snap. If your friends using Snapchat have linked their account to Bitmoji, it will display a special sticker Friendmoji when sending chat messages or commenting their Snap.",
            "/assets/ImagesPresentation/Bitmoji/review12_5.png",
        ],
        score: 3.5,
    },
    {
        id: 4,
        name: 'Desmos',
        urlApp: 'https://whiteboard.fi',
        urlLogo: 'https://drive.google.com/uc?id=1T0Tk_guSHmUheucp-3xr85kMeOXWE8xT&export=download',
        subTitle: 'Create and test mathematical procedures',
        functionality: 3,
        applicability: 6,
        originality: 9,
        ease: 4,
        views: 27,
        likes: 0,
        description: 'Desmos is a new generation graphic calculator; it can be accessed online using a browser, it’s free and doesn’t need installation. The aim of this app is to provide to teachers and students a simple and effective tool to create mathematical procedures, to plot functions and to interact through graphical cursors.',
        categories: ["Diagrams, graphics and images", "Others"],
        tags: ["calculator", "mathematics", "operation", "teacher", "student", "graphic", "graphics", "formula"],
        typology: ["Web app", "Android App", "IOS App"],
        Sign_up_to_create_products: "Optional",
        Sign_up_to_access_artefacts: "No registration",
        Registration_notes: "The application is free and usable without registration, but it would be better to sign-up to be able to save the mathematical procedures in a personal dashboard.",
        Plan_and_Pricing: "",
        Free_plan_limits: "",
        Catalog_of_user_contents: "Public",
        Available_in_Italian_language: "Yes",
        Advertisement: "No",
        Complexity: 6,
        Bloom_level: ["Remember", "Understand", "Apply", "Analyze", "Evaluate", "Create"],
        Documentation: ["Official page ", "https://learn.desmos.com/", "wikipedia ", "https://en.wikipedia.org/wiki/Desmos", "(graphing) another short tutoria", "https://www.youtube.com/watch?v=cJ8G-XXDo-w"],
        Product_examples: ["Example", "https://www.youtube.com/watch?v=cJ8G-XXDo-w"],
        Specific_subjects: ["Mathematics", "Scientific disciplines"],
        urlPresentazione: 'https://www.youtube.com/watch?v=krQSdCej0FY&list=PLXvp1RJPZGU4sn0vVotIV_wspo3cUWbNU&index=70',
        urlTutorial: 'https://www.youtube.com/watch?v=5BpKOfq-H58',
        presentation: [
            "This screenshot shows the main page of Desmos. Thanks to keypad visible below, a user can create a mathematical procedure writing the expression on the left side of the page which will be plotted on the right. Each graph is customizable in the scales of the axes and the grid. In each step of the procedure it is possible to insert functions, equations, comments and tables containing discrete values. Furthermore it is possible to access to a lot of pre-made interesting examples and it is possible to define parameters which will be associated to cursors to permit the user to value interactively their influence on graphic representation.",
            "/assets/ImagesPresentation/Desmos/review23_1.png",
            "Desmos offers also an entire section dedicated to teachers and students that enable teachers to launch interactive activities with their students, monitoring in real time the responses and the progress of each student. The following figure shows the monitor page where teacher can control in real time the progress of the entire class.",
            "/assets/ImagesPresentation/Desmos/review23_2.png",
            "The following image shows the current execution of the work (challenge slide) performed by a specific student.",
            "/assets/ImagesPresentation/Desmos/review23_3.png",
        ],
        score: 3.8,
    },
    {
        id: 5,
        name: 'Duolingo',
        urlApp: 'https://whiteboard.fi',
        urlLogo: 'https://drive.google.com/uc?id=1T0Tk_guSHmUheucp-3xr85kMeOXWE8xT&export=download',
        subTitle: 'Learn a language',
        functionality: 3,
        applicability: 6,
        originality: 9,
        ease: 4,
        views: 46,
        likes: 3,
        description: 'With the Duolingo app you can practice and improve your knowledge of English, French, Spanish or German.. The app offers different exercises, that goes from writing to listening, and they last from: 5, 10, 15, or 20 minutes per day.',
        categories: ["Gamification", "Others"],
        tags: ["language", "foreign", "exercise", "english", "french", "german", "improve", "learn", "game", "gamification", "level", "guide"],
        typology: ["Web app", "Android App", "IOS App", "Windows Mobile App"],
        Sign_up_to_create_products: "Optional",
        Sign_up_to_access_artefacts: "No registration",
        Registration_notes: "You can sign up with your Google account or Facebook.",
        Plan_and_Pricing: "",
        Free_plan_limits: "There are no limits.",
        Catalog_of_user_contents: "No",
        Available_in_Italian_language: "Yes",
        Advertisement: "No",
        Complexity: 2,
        Bloom_level: ["Remember", "Understand", "Apply", "Analyze", "Evaluate"],
        Documentation: ["Official page of support ", "https://support.duolingo.com/hc/en-us"],
        Product_examples: [],
        Specific_subjects: [],
        urlPresentazione: 'https://www.youtube.com/watch?v=N2EtfN1l2XI',
        urlTutorial: 'https://www.youtube.com/watch?v=8OebgtUjLg4',
        presentation: [
            "This is the homepage of Duolingo. To begin you have to click “Get started”. After you have the possibility to choose which language you want to exercise: English, French, Spanish or German. After choosing the language, it's time to decide the daily goal. You can choose to do exercises for: 5, 10, 15 or 20 minutes a day. Then you'll be asked if you want to create a personal profile for achieving your final goal, but this is not necessary. Next, the app will ask if you are familiar with the language and give you the option to take an exam to verify your level.",
            "/assets/ImagesPresentation/Duolingo/review143_1.png",
            "After signing up, the following screen will appear. Here you will be able to keep track of your progress and access the various lessons, read stories in English, discuss with other people in the Duolingo forums, access the dictionary and the list of words learned and add other languages you want to learn.",
            "/assets/ImagesPresentation/Duolingo/review143_2.png",
        ],
        score: 4.6,
    },
    {
        id: 6,
        name: 'EasyBib',
        urlApp: 'https://whiteboard.fi',
        urlLogo: 'https://drive.google.com/uc?id=1T0Tk_guSHmUheucp-3xr85kMeOXWE8xT&export=download',
        subTitle: 'Generate citations and bibliographies',
        functionality: 3,
        applicability: 6,
        originality: 9,
        ease: 4,
        views: 19,
        likes: 1,
        description: 'EasyBib is an application addressing mainly students and researchers, that supports the user in the draft of the bibliography of a research, article or a thesis, allowing to make bibliographic research as well as generate the citations in different standard formats.',
        categories: ["Others"],
        tags: ["bibliography", "school", "research", "quote", "student", "information", "source", "thesis", "degree", "generator"],
        typology: ["Web app", "Android App", "IOS App", "Windows Mobile App"],
        Sign_up_to_create_products: "Optional",
        Sign_up_to_access_artefacts: "No registration",
        Registration_notes: "The registration can be made through Facebook, Google or by inserting: name, surname, email address and password.",
        Plan_and_Pricing: "https://www-secure.easybib.com/products/easybibpro-5?from=savetime-alert",
        Free_plan_limits: "With the free profile you have: presence of advertising, a minor availability of formats and furthermore a limited cloud for the backup of the citations.",
        Catalog_of_user_contents: "Public",
        Available_in_Italian_language: "No",
        Advertisement: "Yes",
        Complexity: 5,
        Bloom_level: ["Remember", "Apply", "Analyze"],
        Documentation: ["Guide on the creation of the citations ", "https://www.easybib.com/guides/?from=nav"],
        Product_examples: [],
        Specific_subjects: [],
        urlPresentazione: 'https://www.youtube.com/watch?v=L2QZRDrn7Q4',
        urlTutorial: 'https://www.youtube.com/watch?v=sPOl9lWEUcY',
        presentation: [
            "You can use Easybib without necessarily registering. The main purpose of this app is to help, mainly the students, creating citations to insert into a research or a thesis. Easybib allows you to find details of different types of contents (websites, books, magazines...). Furthermore, it offers the possibility to visualize the various citations in multiple formats beside the ones you can see in the following picture (MLA8, MLA7, APA, Chicago). You only have to click on “More” and select the desired format (some formats are only available to users who have chosen the Pro account). After selecting the right option, you only have to click on “Cite This” and Easybib will find and memorize our source in a few seconds.",
            "/assets/ImagesPresentation/EasyBib/review279_1.png",
            "So by clicking on “All 59 options” the full list of the options offered by Easybib will appear.",
            "/assets/ImagesPresentation/EasyBib/review279_2.png",
            "If, for example, we are working on a document using as a source the book “Sociologia generale” by Croteau and Hoynes and using some citations deriving from these authors, you will only have to write the title of the manual after selecting the option “book” and the app will find all the books with that title, even ours, providing us, in a brief time, authors, publisher and publication date. In fact, as you can see in the picture, the third book of the column is the one we’ve used. You will only have to click on “Cite this” and it will be memorized.",
            "/assets/ImagesPresentation/EasyBib/review279_3.png",
            "At this point Easybib selects in an accurate and schematic way the title, when and from whom it has been published and at the end the authors of the book we want to cite. The only thing left is to click on “Continue to the final step” in order to be able to access the final step of the citation.",
            "/assets/ImagesPresentation/EasyBib/review279_4.png",
            "In this section Easybib automatically creates an already filled in table, in which you can make changes in case of mistakes; once you completed the form you can pass on to the definitive creation of the citation.",
            "/assets/ImagesPresentation/EasyBib/review279_5.png",
            "As we can notice, the citation we needed is ready, so we can easily copy it and paste it into our document solving so, in a few minutes, a work that would have required more time.",
            "/assets/ImagesPresentation/EasyBib/review279_6.png",
        ],
        score: 4.0,
    },
    {
        id: 7,
        name: 'JellyCam',
        urlApp: 'https://whiteboard.fi',
        urlLogo: 'https://drive.google.com/uc?id=1T0Tk_guSHmUheucp-3xr85kMeOXWE8xT&export=download',
        subTitle: 'Create stop-motion clips',
        functionality: 3,
        applicability: 6,
        originality: 9,
        ease: 4,
        views: 69,
        likes: 0,
        description: 'JellyCam is an open-source software for creating stop-motion movies.The application allows you to shoot video clips by using photos on your computer or instant photos captured by the webcam.After choosing the images, you can organize them into a sequence. Later on you can choose the number of seconds for each frame.Jellycam also allows you to insert a soundtrack for the video.Once the work is finished, you can export the video or upload it directly to YouTube.',
        categories: ["Others", "Video making & enrichment", "Animations"],
        tags: ["video", "making", "stop-motion", "stopmotion", "motion"],
        typology: ["Windows Desktop App", "MacOS App"],
        Sign_up_to_create_products: "No registration",
        Sign_up_to_access_artefacts: "No registration",
        Registration_notes: "Registration is not expected but it is mandatory to enter name, surname and email address to download the application.",
        Plan_and_Pricing: "https://selz.com/it/item/52f8ae8fa1416c0558b75611",
        Free_plan_limits: "",
        Catalog_of_user_contents: "No",
        Available_in_Italian_language: "No",
        Advertisement: "No",
        Complexity: 3,
        Bloom_level: ["Remember", "Create"],
        Documentation: ["Short presentation in Italian of the App ", "https://www.robertosconocchini.it/lavorare-con-i-video/3211-creare-video-con-la-tecnica-dello-stop-motion-jellycam.html"],
        Product_examples: [],
        Specific_subjects: [],
        urlPresentazione: 'https://www.youtube.com/watch?v=82IKj6UsU1M',
        urlTutorial: 'https://www.youtube.com/watch?v=oh1MLlgT7eA',
        presentation: [
            'Jellycam is a fun and easy to use application.This is the page that allows you to download the application: just click on the purple "take it now" button.',
            "/assets/ImagesPresentation/JellyCam/review171_1.png",
            "To continue it will be essential to fill in some fields as shown:",
            "/assets/ImagesPresentation/JellyCam/review171_2.png",
            "After downloading the application, the main program screen opens.",
            "/assets/ImagesPresentation/JellyCam/review171_3.png",
            'The application is very intuitive, you can take pictures by clicking on the blue "take pic" button as many times as you wish. In the frame bar you can select, deselect, duplicate, reverse sequence order or delete photos (in order).In the right screen you can see your video. You can also choose the time for each frame so as to lengthen or shorten your movie.Here is a description of the toolbar on the left:',
            "/assets/ImagesPresentation/JellyCam/review171_4.png",
            "Views: Make: creates the video Edit: look at the pics you have taken Watch: watch the videos you have made About: All the infos about the App Make Movie: Webcam: take your screenshot! Picture Files: choose the pics that will be part of your video Soundtrack: choose your soundtrack Title Screen: you can add sentences to your video Create video: you can save your video in .flv format on your pc or upload it directly on Youtube.",

        ],
        score: 4.2,
    },
    {
        id: 8,
        name: 'Loopy',
        urlApp: 'https://whiteboard.fi',
        urlLogo: 'https://drive.google.com/uc?id=1T0Tk_guSHmUheucp-3xr85kMeOXWE8xT&export=download',
        subTitle: 'A tool for simulation of systems',
        functionality: 3,
        applicability: 6,
        originality: 9,
        ease: 4,
        views: 12,
        likes: 0,
        description: 'Loopy is an Open source web application, that allows the creation of interactive and animated simulations, made of circles and arrows. Simulations can be about all kind of different topics, like technology, environment, psychology or economy, and can be used to illustrate cause and effect concepts, or to create interactive mental maps. This app can be useful for a blog enrichment or an oral presentation made with simulations, and also for class works, by facilitating the comprehension of difficult topics and systems. Everyone can see, play and change original simulations, thus making a contribution.',
        categories: ["Others", "Animations", "Designing & Planning", "Diagrams, graphics and images", "Presentations"],
        tags: ["schema", "combination", "system", "simulation", "think", "learn", "simulate"],
        typology: ["Web app"],
        Sign_up_to_create_products: "No registration",
        Sign_up_to_access_artefacts: "No registration",
        Registration_notes: "No registration required.",
        Plan_and_Pricing: "",
        Free_plan_limits: "",
        Catalog_of_user_contents: "Public",
        Available_in_Italian_language: "No",
        Advertisement: "No",
        Complexity: 3,
        Bloom_level: ["Understand", "Apply", "Analyze", "Evaluate", "Create"],
        Documentation: ["Informative article (in english)", "https://medium.com/@edutechreviews/loopy-an-easy-tool-for-interactive-simulations-a2500de98eab", "Informative article (in italian)", "http://bottegadidattica.blogspot.com/2019/03/mappe-animate-con-loopy-videotutorial.html"],
        Product_examples: ["A scheme example about anxiety and depression", "https://ncase.me/loopy/v1.1/?data=[[[1,198,285,0,%22depression%22,0],[2,531,282,0,%22doing%2520things%22,4],[3,367,115,0,%22de-motivation%22,1],[4,702,116,0,%22fear%2520of%2520mistakes%22,1],[5,860,289,0,%22anxiety%22,0],[6,699,468,0,%22accepting%2520mistakes%22,4],[7,364,473,0,%22feeling%2520good%22,4]],[[2,7,59,1,0],[2,6,-61,1,0],[6,5,-59,-1,0],[5,4,-57,1,0],[4,2,-53,-1,0],[3,2,56,-1,0],[1,3,66,1,0],[7,1,63,-1,0]],[[365,296,%22a%2520possible%250Asystems-level%250Aexplanation%2520for%250Awhy%2520depression%2520%2526%250Aanxiety%2520are%2520not%2520just%250Aco-morbid%252C%2520but%250AMUTUALLY%2520SELF-%250AREINFORCING%22],[695,300,%22CHALLENGE%253A%250A%250Adraw%2520%2526%2520simulate%250Ayour%2520OWN%2520mental%250Afeedback%2520loops%22]],7]"],
        Specific_subjects: [],
        urlPresentazione: 'https://www.youtube.com/watch?v=KBZpu8LjwDI',
        urlTutorial: 'https://www.youtube.com/watch?v=R-zhjx6IZV8',
        presentation: [
            "Accessing the main page, the logo will be displayed, followed by a brief introduction to this app.",
            "/assets/ImagesPresentation/Loopy/review313_1.png",
            "The following screenshot shows different activities that can be carried out with Loopy, that is experiment with various simulations, model systems by drawing circles and arrows, and change the simulations created by others.",
            "/assets/ImagesPresentation/Loopy/review313_2.png",
            "The next screenshot shows three examples of systems, about different topics; it is also explained what Loppy can be useful for, and, finally, by clicking on “Try out Loopy” you can start drawing a system from scratch.",
            "/assets/ImagesPresentation/Loopy/review313_3.png",
            "By clicking on one of the exemples, it will be possible to have access to the selected model and change it. The menu panel on the left side has four icons: with the pencil, you can add and modify an inscription by clicking on it, or create a circle and an arrow; with the symbol T you can change the name, the colour and the starting amount of the circle; with the hand icon, you can change the position of the elements in the system; finally, the rubber is used to erase the unwanted elements. Below the workplane, you will find the “Play” button: by clicking on it, the arrows will interact with the created systems at the desired speed.",
            "/assets/ImagesPresentation/Loopy/review313_4.png",
            "The panel on the right side offers various possibilities: you can take a glimpse of different examples of models created by other people, and the option “how to” gives a brief explanation of the various modifications that can be made with the icons previously explained. The model, after being created, can be saved as a link, as a file, converted in a GIF, or embedded in a website.",
            "/assets/ImagesPresentation/Loopy/review313_5.png",
        ],
        score: 3.9,
    },
    {
        id: 9,
        name: 'Pixton',
        urlApp: 'https://whiteboard.fi',
        urlLogo: 'https://drive.google.com/uc?id=1T0Tk_guSHmUheucp-3xr85kMeOXWE8xT&export=download',
        subTitle: 'Create comic stories',
        functionality: 3,
        applicability: 6,
        originality: 9,
        ease: 4,
        views: 50,
        likes: 0,
        description: 'Pixton is a web application, useful to create online comics strips. You can also start from stories created by other users of the community. Pixton, makes available for many people, editable places, objects, which can be inserted in the balloon by changing the position and appearance of each object. With Pixton also you can share the comics you made, through the various social networks.',
        categories: ["Diagrams, graphics and images", "Others", "Storytelling"],
        tags: ["comics", "student", "teacher", "parents", "story", "idea", "learning", "creativity", "communication"],
        typology: ["Web app"],
        Sign_up_to_create_products: "Compulsory",
        Sign_up_to_access_artefacts: "Compulsory",
        Registration_notes: "",
        Plan_and_Pricing: "https://app.pixton.com/",
        Free_plan_limits: "",
        Catalog_of_user_contents: "Protected",
        Available_in_Italian_language: "No",
        Advertisement: "No",
        Complexity: 5,
        Bloom_level: ["Apply", "Create"],
        Documentation: [],
        Product_examples: [],
        Specific_subjects: [],
        urlPresentazione: 'https://www.youtube.com/watch?v=BqvSLuvYTBA',
        urlTutorial: 'https://www.youtube.com/watch?v=or5rA0ALlHo',
        presentation: [
            "The following is the Pixton home screen. Here you can proceed with login or registration, choosing from four possible accounts: educators, students, parents, business. You will be able to register through Google, Microsoft, or Facebook accounts.",
            "/assets/ImagesPresentation/Pixton/review67_1.png",
            'After registering, in this case it was with an educator account, the app dashboard will appear. Here, teachers will be able to see the students who have joined the class or they can share the link with them through the "student join link" voice; then for each student it will be possible to view the comics created.',
            "/assets/ImagesPresentation/Pixton/review67_2.png",
            "Both students and teachers can create their own comics. This is the editing screen for creating comics. In the menu on the left you can add different panels to create a sequence of images. In the top menu you can add a background, characters and text clouds. Also you can make the comic brighter or darker and insert a photo imported from your PC by clicking on the menu at the bottom right.",
            "/assets/ImagesPresentation/Pixton/review67_3.png",
        ],
        score: 3.3,
    },
    {
        id: 10,
        name: 'Quizlet',
        urlApp: '',
        urlLogo: '',
        subTitle: 'Create and interact with flashcards',
        functionality: 3,
        applicability: 6,
        originality: 9,
        ease: 4,
        views: 139,
        likes: 1,
        description: 'Quizlet offers various tools for learning and memorization of educational contents. You can find materials in a public wide database or create new quizlets, even starting from an existing one. Once created a quizlet, which is a group of couples (ex.: noun/definition) it’s possible to use it in various forms (flashcards, quiz, association activity etc.) and share its url.',
        categories: ["Flashcards", "Gamification", "Quizzes", "forms", "surveys", "Groups management"],
        tags: ["study", "learning", "student", "teacher", "school", "education", "activity", "game", "flashcard"],
        typology: ["Web app", "Android App", "IOS App"],
        Sign_up_to_create_products: "Compulsory",
        Sign_up_to_access_artefacts: "No registration",
        Registration_notes: "You can authenticate using your Google or Facebook account or register using your email.",
        Plan_and_Pricing: "https://quizlet.com/upgrade?source=dropdown",
        Free_plan_limits: "You can’t upload your own images, you can’t record audios, you can only create limited classes. Contains display advertising.",
        Catalog_of_user_contents: "Public",
        Available_in_Italian_language: "Yes",
        Advertisement: "Yes",
        Complexity: 4,
        Bloom_level: ["Remember", "Understand", "Analyze", "Evaluate"],
        Documentation: ["Help: ", "https://help.quizlet.com/hc/it/", "Blog: ", "https://quizlet.com/blog"],
        Product_examples: ["Example ", "https://quizlet.com/86746556/match"],
        Specific_subjects: [],
        urlPresentazione: 'https://www.youtube.com/watch?v=65XLrN4rWrw&index=111&list=PLXvp1RJPZGU4sn0vVotIV_wspo3cUWbNU',
        urlTutorial: 'https://www.youtube.com/watch?v=V6AQNAVxAXU',
        presentation: [
            "The following is the home screen of Quizlet. Here you can proceed with the registration through Facebook, Google or your email account.",
            "/assets/ImagesPresentation/Quizlet/review77_1.png",
            "Once you have registered, the following screen will appear which is the app dashboard. From here you can proceed with creating your class or creating sets to share with your students.",
            "/assets/ImagesPresentation/Quizlet/review77_2.png",
            "The following is the editing screen where you can create sets. It will be necessary to give them a name and a description. Then you'll have to enter the various terms with their definitions and you can create it and save it in your dashboard. You can decide whether to share it with your class or with other users via URL.",
            "/assets/ImagesPresentation/Quizlet/review77_3.png",
            "The following screen shows how you can use the sets to learn. In the menu on the right you can choose different learning modes.",
            "/assets/ImagesPresentation/Quizlet/review77_4.png",
        ],
        score: 4.5,
    },
    {
        id: 11,
        name: 'Tinytap',
        urlApp: 'https://whiteboard.fi',
        urlLogo: 'https://drive.google.com/uc?id=1T0Tk_guSHmUheucp-3xr85kMeOXWE8xT&export=download',
        subTitle: 'Educational games and interactive lessons',
        functionality: 3,
        applicability: 6,
        originality: 9,
        ease: 4,
        views: 65,
        likes: 1,
        description: 'Tinytap is a social platform that allows families, teachers and students to learn from one another by creating and sharing educational games every day. It allows you to play, learn and gather information through the use of images, quizzes, e-books, soundboards, interactive presentations, photo albums.',
        categories: ["Gamification", "Animations", "Groups management", "Quizzes, forms, surveys"],
        tags: ["game", "interactive", "lesson", "educational", "school", "class", "student", "teacher", "collection", "activity"],
        typology: ["Web app", "Android App", "IOS App"],
        Sign_up_to_create_products: "Compulsory",
        Sign_up_to_access_artefacts: "No registration",
        Registration_notes: "",
        Plan_and_Pricing: "https://www.start.tinytap.com/educational-kids-games-en?email_only=true&show_paypal=true&show_only=both&hide_coupon=true&from_ads=false&hide_payment_request_button=true&paypal_redirect=true&hide_stripe=false&show_cc_toggle=text&ad_id=organic&",
        Free_plan_limits: "The creation of games and various activities requests the download of the app from the Store.",
        Catalog_of_user_contents: "Public",
        Available_in_Italian_language: "Yes",
        Advertisement: "No",
        Complexity: 5,
        Bloom_level: ["Remember", "Understand", "Apply", "Analyze", "Evaluate", "Create"],
        Documentation: ["Description and functions of the app ", "https://insegnantiduepuntozero.wordpress.com/2014/07/08/crea-la-tua-learning-app-con-tinytap/"],
        Product_examples: [],
        Specific_subjects: [],
        urlPresentazione: 'https://www.youtube.com/watch?v=KI1YFEH23lc',
        urlTutorial: 'https://www.youtube.com/watch?v=rUPE1ej3pjI#action=share',
        presentation: [
            "Tinytap is a simple and easy to use app. It’s compatible with iOs and Android, but it’s possible to access the games and the activities via the Desktop of your PC.",
            "/assets/ImagesPresentation/Tinytap/review242_1.png",
            "The app is available in 46 languages. Select the age group for the group of activities.",
            "/assets/ImagesPresentation/Tinytap/review242_2.png",
            "Login is not obligatory, but it’s necessary to create class groups and assign homework.",
            "/assets/ImagesPresentation/Tinytap/review242_3.png",
            "It’s possible to view the activities and homework that have been assigned in the class group and their development by each participant with the relative information (date and time of execution, percentage, time spent).",
            "/assets/ImagesPresentation/Tinytap/review242_4.png",
            "The activities/lessons created can be made public or visible only inside the interested class group. To create a game, choose the option “Create new course” and fill out the form; however, there is a payment to be made.",
            "/assets/ImagesPresentation/Tinytap/review242_5.png",
            "/assets/ImagesPresentation/Tinytap/review242_6.png",
            "/assets/ImagesPresentation/Tinytap/review242_7.png",
            "/assets/ImagesPresentation/Tinytap/review242_8.png",
            "Tinytap includes a variety of games and activities of different genres, related to different disciplines (English, Italian, geography, history, ecc…) through the use of images, quizzes, e-books, soundboards, interactive presentations, photos, ecc.",
            "/assets/ImagesPresentation/Tinytap/review242_9.png",
            "/assets/ImagesPresentation/Tinytap/review242_10.png",
        ],
        score: 3.7,
    },
    {
        id: 12,
        name: 'Cram',
        urlApp: '',
        urlLogo: '',
        subTitle: 'Studying with flashcards',
        functionality: 3,
        applicability: 6,
        originality: 9,
        ease: 4,
        views: 74,
        likes: 0,
        description: 'The app Cram is based on the use of flashcards, in other words the sum of cards which contain in both sides one information and a description. The flashcards allow you to memorize the concepts through their receptive consultation and the fulfillment of association, quiz and games. Cram, beside making available millions of flashcards created by the users community allows the user to personalize and define new ones.',
        categories: ["Flashcards", "Gamification", "Quizzes, forms, surveys"],
        tags: ["exercise", "test", "game", "gamification", "memorize", "study", "school", "student", "education", "flashcard", "learning", "concept", "definition", "description", "fun"],
        typology: ["Web app", "Android App", "IOS App"],
        Sign_up_to_create_products: "Compulsory",
        Sign_up_to_access_artefacts: "No registration",
        Registration_notes: "The registration is required once you want to create your own flashcards or access the contents for which is expected a subscription.",
        Plan_and_Pricing: "https://www.cram.com/plans",
        Free_plan_limits: "With the free account is possible to access flashcards whereas to access or create study materials, it is necessary to subscribe a payment profile.",
        Catalog_of_user_contents: "Public",
        Available_in_Italian_language: "No",
        Advertisement: "Yes",
        Complexity: 4,
        Bloom_level: ["Remember", "Understand", "Evaluate", "Create"],
        Documentation: ["Article in the use of Cram in the study of phisics:", "http://www.marcellodevita.net/pags/spip.php?article210", "Tutorial:", "https://es.slideshare.net/aberriolo/tutorial-cram-mobile", "Wikipedia page dedicated to Cram:", "https://en.wikipedia.org/wiki/Cram.com", "Community of students and teachers which use like a learning method the flashcards of Cram:", "https://quizlet.com/256101685/cram-flash-cards/"],
        Product_examples: ["Example of flashcards", "https://www.cram.com/flashcards/chapter-7-vocabulary-313514", "Text where you can consult the free version:", "https://www.cram.com/essay/Terrorism-Terrorism-And-Terrorism-In-The-United/FKP5HUH9CX5W"],
        Specific_subjects: [],
        urlPresentazione: 'https://www.youtube.com/watch?v=J0wkrtTQK9A',
        urlTutorial: 'https://www.youtube.com/watch?v=SEqqTbpfebI&t=6s',
        presentation: [
            "The homepage of Cram in the superior part presents the research bar where you can insert the key notes which allow you to find the flashcards in which we are interested in and button that allows you to create new ones. Down below the flashcards are divided in categories and there is written the number of flashcards available, the number of flashcards added during the week and the number of users.",
            "/assets/ImagesPresentation/Cram/review139_1.png",
            "Clicking on one of the categories suggested it opens the page that presents the subcategory of the selected category regarding specific topics.",
            "/assets/ImagesPresentation/Cram/review139_2.png",
            "Choosing one of these subcategories, you can visualize and use the flashcards. The consulting and the following memorization of the flashcards are managed in different stages. There are also inserted the instructions to use the commands of the keyboard and the buttons to share, print, download and copy flashcards.",
            "/assets/ImagesPresentation/Cram/review139_3.png",
            "The second phase regards the memorization. This phase can be personalized by the user thanks to the buttons present on the right. It appears a question with different possible answers and here he users has simply to decide to answer by voice to then verify if the given answer is correct to then click on the buttons “I was wrong” or “I got it right”.",
            "/assets/ImagesPresentation/Cram/review139_4.png",
            "/assets/ImagesPresentation/Cram/review139_5.png",
            "Or, the user can choose an alternative method of answering consisting on writing the answer which he thinks is correct so in this case is the app that checks the answer.",
            "/assets/ImagesPresentation/Cram/review139_6.png",
            "The third educational phase is represented by tests. Also this phase can be personalized by the user in different ways using the methods available on the right.",
            "/assets/ImagesPresentation/Cram/review139_7.png",
            "The fourth and final phase is represented by games. The games are two: Jewels of Wisdom and Stella Speller. The first one consists in uniting the bricks on the right with the ones on the left based on the relationship between the displayed words; the second one consists into shooting the meteorites which bring the letters useful to create the right word.",
            "/assets/ImagesPresentation/Cram/review139_8.png",
            "Cam also allows you to create your own flashcards. First it is required a description of the flashcard containing the title, the regarding subject, a brief presentation and the choice regarding the access of other users. Then you have to create the single flashcard in which you have to insert the frontal side on the left and the back side on the right.",
            "/assets/ImagesPresentation/Cram/review139_9.png",
        ],
        score: 3.8,
    },
    {
        id: 13,
        name: 'Studyblue',
        urlApp: '',
        urlLogo: '',
        subTitle: 'Find and create flashcards',
        functionality: 3,
        applicability: 6,
        originality: 9,
        ease: 4,
        views: 50,
        likes: 0,
        description: 'Studyblue is a platform that provides tools like flashcard, notes and guides for studying. Students can create, share and confront flashcards, drawing from a broad and accessible library of online resources. Studyblue allows students to study in a more efficient way: it allows the possibility to test your level of understanding through different types of online tests/quizzes.',
        categories: ["Flashcards", "Quizzes, forms, surveys"],
        tags: ["learning", "flashcard", "activity", "study", "school", "student", "education", "test", "quiz", "online"],
        typology: ["Web app", "Android App", "IOS App", "Chrome extension"],
        Sign_up_to_create_products: "Compulsory",
        Sign_up_to_access_artefacts: "No registration",
        Registration_notes: "Registration is mandatory and can be made via your Facebook or Google accounts, or by inserting: name, surname, e-mail address and password.",
        Plan_and_Pricing: "https://www.chegg.com/flashcards#account/proAwareness",
        Free_plan_limits: "The plan & pricing page is accessible only after authentication. The free profile allows you to see only some of the flashcards inserted by other student and to practise studying with these with various quizzes. Many are obscured and if you wish to use them, you must create a payment account. Furthermore, the free account forces you to make your work public.",
        Catalog_of_user_contents: "Public",
        Available_in_Italian_language: "No",
        Advertisement: "Yes",
        Complexity: 3,
        Bloom_level: ["Remember", "Understand", "Apply", "Analyze", "Evaluate", "Create"],
        Documentation: ["Via this link you have access to a website that is dedicated to reviews of apps made for studying and the education of children. The website gives you a wide view, showing you the functions of benefits of using this app:", "https://learningworksforkids.com/apps/studyblue/", "Tutorial on the YouTube in English that explain in detail how to create flashcrads and how to use them for efficient studying:", "https://www.youtube.com/watch?v=sB6vkNdUPlE", "Video in English published by the magazine for teachers “Teach Hub” that shows and explains the functions of the platform and it underlines its advantages, showing also how the app can be used on mobile devices:", "https://www.youtube.com/watch?v=pgpOh0f0Mz0"],
        Product_examples: ["Example of a maths flashcard:", "https://www.chegg.com/flashcards/2-2-functions-fa5afbff-4c2c-4035-b169-5c901bd29677/deck?referrer=https://www.studyblue.com"],
        Specific_subjects: [],
        urlPresentazione: 'https://www.youtube.com/watch?v=Z0et8HAw9nM',
        urlTutorial: 'https://www.youtube.com/watch?v=XyEoqHk8UQg',
        presentation: [
            "When you register, the app will ask you under which title you’d like to register (student, teacher or other). If you choose student, the next question will be which school you go to, which class you’d like to work on, and the name of your chosen class’ teacher. When you type in what school you go to, a green tick will appear with “Great school” written underneath, as shown below.",
            "/assets/ImagesPresentation/Studyblue/review233_1.png",
            "Aspect of a finished product Once you’ve registered the class topic you want to learn, you can create the flashcards of the contents you will need.",
            "/assets/ImagesPresentation/Studyblue/review233_2.png",
            "Once you’ve created all the flashcards that you find necessary for your study, you will come across a page like the one below.",
            "/assets/ImagesPresentation/Studyblue/review233_3.png",
            "Now you can put yourself to the test with a quiz that will see how much you’ve learned with the flashcards. Click on “Study Now”. A new page will open that will ask you which type of quiz you prefer. I chose the first option. I now have the possibility to test my studying against others.",
            "/assets/ImagesPresentation/Studyblue/review233_4.png",
            "The window will open on the left with the word you have to learn. You can then turn the flashcard around to see the definition. If you remembered it correctly, click on the green thumb up. If not, click on the red thumb down.",
            "/assets/ImagesPresentation/Studyblue/review233_5.png",
            "/assets/ImagesPresentation/Studyblue/review233_6.png",
            "Lastly, the platform will show a page in which there will be an assessment of your knowledge and you will be invited to “Study Again”.",
            "/assets/ImagesPresentation/Studyblue/review233_7.png",
            "The dashboard’s appearance. Flashcards with their assessment, your class topics, your activities will all appear on the dashboard. From here, you can create new works (new class topics, new flashcards groups). You can also search for flashcards created by other users to study different topics.",
            "/assets/ImagesPresentation/Studyblue/review233_8.png",
            "The authoring page’s appearance. In the authoring page you have the possibility to create new flashcards by clicking on “Make Cards”. In the box that opens on top you can write the topic and the description in the one below. When saving (“Save and Exit”) you’ll have to give a title to your work and insert inside a class of topic by inserting it inside a class of topics. The free profile, as stated before, obligates you to make your work public. By clicking on “Import” you can also import files in .xls, .xlsx, .csv: this will be organised like files in two columns: in the first there will be the topic and in the second one the description. If you click on “Settings” you can choose a title and a class of topics in which you can insert your work. Clicking on “Matching Cards”, I can choose whether or not to receive helpful tips for other flashcards that are similar to the ones I’m inserting (through “Hide” and “Show”). posso decidere se ricevere o meno suggerimenti (attraverso i pulsanti “Hide” e “Show”).",
            "/assets/ImagesPresentation/Studyblue/review233_9.png",
        ],
        score: 4.2,
    },
    {
        id: 14,
        name: 'WordsTool',
        urlApp: '',
        urlLogo: '',
        subTitle: 'Flashcards based activities',
        functionality: 3,
        applicability: 6,
        originality: 9,
        ease: 4,
        views: 22,
        likes: 0,
        description: 'WordsTool is a web application that allows you to create flashcards with text, images and audio. Moreover, it allows you to create virtual classes and involve students in different types of activities for example dictation, pairings, anagrams and others. There is also a function to control students.',
        categories: ["Flashcards", "Gamification", "Groups management"],
        tags: ["words", "pronunciation", "task", "anagram", "gamification", "class", "flashcard"],
        typology: ["Web app"],
        Sign_up_to_create_products: "Compulsory",
        Sign_up_to_access_artefacts: "Compulsory",
        Registration_notes: "Registration in necessary both to create sets of flashcard and also for students to carry out the activities assigned by teacher. As an alternative to registration you can access with your Facebook and Google accounts.",
        Plan_and_Pricing: "https://wordstool.com/prices",
        Free_plan_limits: "The free profile allows to create flashcards, virtual classes and assign tasks and their monitoring.",
        Catalog_of_user_contents: "Protected",
        Available_in_Italian_language: "No",
        Advertisement: "No",
        Complexity: 7,
        Bloom_level: ["Remember", "Understand", "Apply", "Analyze", "Evaluate", "Create"],
        Documentation: ["The Facebook page of the application", "https://www.facebook.com/pg/wordstool/posts/?ref=page_internal"],
        Product_examples: ["Example of how to create flash cards", "https://wordstool.com/for-students"],
        Specific_subjects: [],
        urlPresentazione: 'https://www.youtube.com/watch?v=Rp1ON-gg8U0',
        urlTutorial: 'https://www.youtube.com/watch?v=dpmpov0TPdc',
        presentation: [
            "This is how the homepage looks like. Through the links at the top right you can proceed with the login “Log in” or with the registration “Register”.",
            "/assets/ImagesPresentation/WordsTool/review319_1.png",
            "Once authenticated, it appears a summary of the recent activities that we have done in our profile.",
            "/assets/ImagesPresentation/WordsTool/review319_2.png",
            "The following picture shows an example of a card relating to the word “t-shirt” belonging to a set of flashcards: the first two sentences are examples containing that word. The italian translation is also visible followed by the word with near the icon to listen to the pronunciation. Below there is the word definition and a picture that represents it.",
            "/assets/ImagesPresentation/WordsTool/review319_3.png",
            "At the top of our dashboard we will find: “Discover” to view some examples of flashcards; “Assigned” to list all tasks assigned to students: before being able to assign them to a class, the tasks must be defined in the task section by choosing the date and the time to start, deadline, the class or single students to assign it and description of the activity to do; “Students” to list classes and students with the possibility to invite others; “Words” to create flashcards and see those create previously; “Tasks” to list tasks based on flashcards and create new ones. By clicking on the icon with our initial you can see the setting of your personal profile.",
            "/assets/ImagesPresentation/WordsTool/review319_4.png",
            "The picture below shows the editing page to create a single flashcard belonging to a set. In the center we write the word of the flashcard, above it is possible to write two phrases where the word is present and below these, a box to insert a definition, a synonym, an antonym, a picture to represent the word and an audio file for the pronunciation. It is allowed to change flashcard at any time and group flashcards together into a folder.",
            "/assets/ImagesPresentation/WordsTool/review319_5.png",
            "The picture below shows the page for creating a “task”. Each task could be divided into different sections that can customized with a freely chosen name (fase 1, fase 2 in the example). Each section could also include different types of tasks which can be inserted or removed at any time. It is possible to define a time limit to carry out the exercises, which can be different for each section. Moreover, it is possible to create templates for recurring tasks. Each task can contain exercises concerning three different categories: “words”, “exercises” and “extras”. In the “words” category you can choose: “whole cards”: to assign exercise on the content of each flashcard; “pronunciation”: to do pronunciation exercises; “synonym/antonym”: for exercises on synonym/antonym; “context”: to practise using words in a context; “meaning”: to practise the words meaning; In the “exercise” category you can choose: “fillword”: different kind of completion exercises, for example, given a word in the question, its definition is requested in the answer; “anagram”: anagrams with exercises of different kind, for example the question is a meaning or an example and the answer is the corresponding word to be constructed based on the letters that appear on the screen; “mcq”: multiple choice between different options; “dictaction”: dictated; “matching”: matching exercises; In the category “extras” it possible to practice with the images associated to words.",
            "/assets/ImagesPresentation/WordsTool/review319_6.png",
            "The following image shows the interface allowing teachers to create the exercises",
            "/assets/ImagesPresentation/WordsTool/review319_7.png",
            "The next picture shows the student-side interface of an association exercise.",
            "/assets/ImagesPresentation/WordsTool/review319_8.png",
            "The following pictures show some exercises that could be assigned. This application also allows to supervise empowerment of students over a period of time.",
            "/assets/ImagesPresentation/WordsTool/review319_9.png",
            "/assets/ImagesPresentation/WordsTool/review319_10.png",
            "/assets/ImagesPresentation/WordsTool/review319_11.png",
            "/assets/ImagesPresentation/WordsTool/review319_12.png",
        ],
        score: 4.0,
    },
    {
        id: 15,
        name: 'TimeToast',
        urlApp: '',
        urlLogo: '',
        subTitle: 'Create interactive timelines',
        functionality: 3,
        applicability: 6,
        originality: 9,
        ease: 4,
        views: 125,
        likes: 10,
        description: 'Timetoast is a web application that allows the creation of time lines, with an engaging and clear interface. Moreover, events inserted along the timelines can be enriched through the inclusion of captions and images, making the app even more intuitive and very practical.',
        categories: ["Storytelling", "Timelines", "Presentations"],
        tags: ["timeline", "time", "enrich", "caption", "image", "easy", "intuitive", "share"],
        typology: ["Web app"],
        Sign_up_to_create_products: "Compulsory",
        Sign_up_to_access_artefacts: "No registration",
        Registration_notes: "To create timelines you need to create an account. Timetoast provides three different types of user profiles:<br>- public (free);<br>- Basic ($ 5.99 / month);<br>- Pro ($ 8.99 / month). <br>The main difference between basic profile and pro profile is the number of users with whom you can interact in collaborative projects, the first profile allows five users while the most expensive up to thirty-five.",
        Plan_and_Pricing: "https://www.timetoast.com/plans",
        Free_plan_limits: "The free profile contains external advertisement and it’s not possible to collaborate with other users or create groups. Finally, there’s no moderation mechanism.",
        Catalog_of_user_contents: "Public",
        Available_in_Italian_language: "No",
        Advertisement: "Yes",
        Complexity: 4,
        Bloom_level: ["Remember", "Understand", "Analyze", "Create"],
        Documentation: ["Slides with step-by-step explanation of account and timeline creation:", "https://www.slideshare.net/main/private_slideshow?path_to_redirect_at=https%3A%2F%2Fwww.slideshare.net%2Flantichi%2Ftimetoast-54348466"],
        Product_examples: ["Timeline Story of Jazz:", "https://www.timetoast.com/timelines/jazz-final-timeline", "Timeline civil war:", "https://www.timetoast.com/timelines/civil-war-timeline-19c4e348-52a9-4072-8c9c-85a97bfc2ed2", "Timeline HTML Story:", "https://www.timetoast.com/time..."],
        Specific_subjects: [],
        urlPresentazione: 'https://www.youtube.com/watch?v=Pa47VwcK4rk&index=64&list=PLXvp1RJPZGU4sn0vVotIV_wspo3cUWbNU',
        urlTutorial: 'https://www.youtube.com/watch?v=kEf_u0qqSu0',
        presentation: [
            "In this image there’s an example of finished product. It’s a timeline about the most important movies in history. As you can see, the interface is simple and intuitive.",
            "/assets/ImagesPresentation/Timetoast/review319_1.png",
            "In this second image there’s the foreground of an event added to the timeline, enriched by an image, a caption, a title and the date.",
            "/assets/ImagesPresentation/Timetoast/review319_2.png",
            "The dashboard looks very simple and practical, from this screen, the user can view and edit his/her own timeline, create new ones and also receive notifications and access the working groups.",
            "/assets/ImagesPresentation/Timetoast/review319_3.png",
            "In the authoring page, first you will see a screen where you can enter the main details of the timeline; as the title, the argument category and cover image.",
            "/assets/ImagesPresentation/Timetoast/review319_4.png",
            'The "Add event" button allows the editing of an historical event, offering the possibility to add external links, pictures and descriptions.',
            "/assets/ImagesPresentation/Timetoast/review319_5.png",
            "The timeline will be finally seen in two different graphic interfaces, thanks to the “Timeline” and “List” buttons.",
            "/assets/ImagesPresentation/Timetoast/review319_6.png",
            "/assets/ImagesPresentation/Timetoast/review319_7.png",
            "the last important page is the plan and pricing screen, which is simple and clear too",
            "/assets/ImagesPresentation/Timetoast/review319_8.png",
        ],
        score: 4.3,
    },
];